### ISSUE TITLE
Create customer login

### ISSUE THREAD

**Issue by haseebakhan10** [haseebakhan10/EngLabProject#43]
We need to create a customer login.  We will also need tests for this

**Comment by haseebakhan10** [comment]
@ryanzzheng570  or @TriMPNhan can you work on this and assign it to yourself?

**Comment by BramSrna** [comment]
The merchant login may need to be changed as well depending on how you guys want to do the customer login. The current merchant login does not use Firebase authentication, it uses our own implementation. If you guys want to stick with our implementation, then it should be good, but if you want to switch to Firebase authentication, merchant login also needs to be updated.

**Comment by haseebakhan10** [comment]
> The merchant login may need to be changed as well depending on how you guys want to do the customer login. The current merchant login does not use Firebase authentication, it uses our own implementation. If you guys want to stick with our implementation, then it should be good, but if you want to switch to Firebase authentication, merchant login also needs to be updated.

I think we should commit to what we already have, it works well and don't want to make too many changes near the deadline. @calvin1088 @ryanzzheng570 @TriMPNhan thoughts?

**Comment by calvin1088** [comment]
I think the current design is fine and considering the video demo is in a few days, we should leave it as is.

**Comment by calvin1088** [comment]
Customer account signup should also automatically login the customer.
