### ISSUE TITLE
Issue Fixes

### ISSUE THREAD

**Issue by calvin1088** [haseebakhan10/EngLabProject#50]
- Fix missing logged in user display in sidebar when clicking cart
- Add text to separate list of items in shop with new item form
- Minor UI improvements

**Comment by haseebakhan10** [comment]
Other improvements:
- When a user or merchant successfully signs up, automatically log them in
- There is a check when adding an item to make sure inventory is a whole number(a message comes up if you don't). When editing an item, add the same thing. Currently if I enter a decimal number in the edit section (1.5) the program crashes.
- We can add an item with no cost and inventory(which makes sense), but for some reason when editing an item either the cost or the inventory cannot be 1. Make the edit item behaviour the same as the add item behaviour.
